## Исключение
По мимо обычного автоматического перехвата исключений в блоке `try`
мы также можем и сами вызывать исключения по своему желанию. Сделать это 
можно 2 способами:

1) Создать свой собственный класс и унаследоваться от общего класса исключений,
   в методе `__init__()` вызвать конструктор родителя.
2) Можно при помощи оператора `raise` вызвать нужное нам исключение из списка
   стандартных исключений и перехватить его в блоке `except`

Существует стандартный набор исключений, из которого можно выбрать требуемое и 
поднимать его при необходимости. К примеру таким образом.

    raise ValueError("Несоответствующее значение")

    raise TypeError('Аргумент должен быть строкой.')


